# Generated by Django 4.2.5 on 2024-12-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_request_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'b',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('days', models.DateField(blank=True, null=True)),
                ('cases', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'covid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GetRequestApiItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'get_request_api_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MbDfsTrans',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('last_modified_by', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_comm_amount', models.FloatField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cbs_client_tran_id', models.BigIntegerField(blank=True, null=True)),
                ('client_id', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_comm_amount', models.FloatField(blank=True, null=True)),
                ('extra_amount', models.FloatField(blank=True, null=True)),
                ('extra_amount_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_comm_amount', models.FloatField(blank=True, null=True)),
                ('hub_corp_comm_amount', models.FloatField(blank=True, null=True)),
                ('imei', models.CharField(blank=True, max_length=255, null=True)),
                ('inst_comm_amount', models.FloatField(blank=True, null=True)),
                ('is_critical', models.BooleanField()),
                ('log_id', models.BigIntegerField(blank=True, null=True)),
                ('max_completion_date', models.CharField(blank=True, max_length=255, null=True)),
                ('originating_unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('process', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_bank_ac', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('req_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('reverse_voucher_number', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_address', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_identification', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_info_id', models.CharField(blank=True, max_length=255, null=True)),
                ('service_scope', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('source_ac', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('tc_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_status', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_no', models.CharField(blank=True, max_length=255, null=True)),
                ('service_option_id', models.BigIntegerField(blank=True, null=True)),
                ('service_provider_id', models.BigIntegerField(blank=True, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=255, null=True)),
                ('exception_message', models.CharField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_bank_qr', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mb_dfs_trans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MbPaymentTran',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ac_no', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('ben_mobile_no', models.CharField(blank=True, max_length=255, null=True)),
                ('cbs_transaction_timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.BigIntegerField(blank=True, null=True)),
                ('cbs_client_tran_id', models.TextField(blank=True, null=True)),
                ('cooperative_commission', models.FloatField(blank=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_commission', models.FloatField(blank=True, null=True)),
                ('http_code', models.IntegerField(blank=True, null=True)),
                ('hub_commission', models.FloatField(blank=True, null=True)),
                ('info_commission', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('needs_resubmission', models.BooleanField(blank=True, null=True)),
                ('payment_amt', models.FloatField(blank=True, null=True)),
                ('payment_initiated_date', models.DateTimeField(blank=True, null=True)),
                ('process_end', models.DateTimeField(blank=True, null=True)),
                ('process_start', models.DateTimeField(blank=True, null=True)),
                ('processed_from', models.IntegerField(blank=True, null=True)),
                ('req_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('response_code', models.IntegerField()),
                ('reverse_vch_no', models.CharField(blank=True, max_length=255, null=True)),
                ('service_id', models.BigIntegerField(blank=True, null=True)),
                ('sms_timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('total_commission', models.FloatField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('vendor_id', models.BigIntegerField(blank=True, null=True)),
                ('vendor_transaction_id', models.TextField(blank=True, null=True)),
                ('vch_no', models.TextField(blank=True, null=True)),
                ('wallet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=255, null=True)),
                ('counter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('exception_message', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ebp_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_status', models.CharField(blank=True, max_length=255, null=True)),
                ('reverse_wallet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.BigIntegerField(blank=True, null=True)),
                ('transaction_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mb_payment_tran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterMappingTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reconcilation_id', models.IntegerField(blank=True, null=True)),
                ('parameter_table_id', models.IntegerField(blank=True, null=True)),
                ('validation', models.IntegerField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'parameter_mapping_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parameter_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReconcilationCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'reconcilation_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationCategory15',
            fields=[
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_id', models.IntegerField(blank=True, null=True)),
                ('drcr_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reconciliation_category_15',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestReconciliationCategory15',
            fields=[
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_id', models.IntegerField(blank=True, null=True)),
                ('drcr_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'test_reconciliation_category_15',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
