# Generated by Django 3.1.7 on 2021-04-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ad_newsproduct_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.nav'),
        ),
    ]
