# Generated by Django 3.1.7 on 2021-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_picture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsproduct',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
