# Generated by Django 4.2.5 on 2023-09-11 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.department')),
            ],
        ),
    ]
