# Generated by Django 4.2.5 on 2023-09-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_department_dept_id_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
