# Generated by Django 4.2.5 on 2023-09-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('emp_code', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emp_app.position')),
            ],
        ),
    ]
