# Generated by Django 3.1.7 on 2021-03-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210316_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offer',
            field=models.BooleanField(default=True),
        ),
    ]
