# Generated by Django 3.1.7 on 2021-03-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='slag',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
