# Generated by Django 4.2.5 on 2023-09-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_model',
            name='title',
            field=models.TextField(),
        ),
    ]
