# Generated by Django 4.2.5 on 2023-09-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_info_model_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_model',
            name='description',
            field=models.CharField(),
        ),
    ]
