# Generated by Django 4.2.5 on 2023-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
